### PR TITLE
Powershell Support

### PR DESCRIPTION
**Pull request by aaroneg**
This should address bug #16 .

### CODE REVIEW

**Comment by aaroneg** [comment]
Updated to match some refactoring requested by jneen.

**Comment by rumpelsepp** [comment]
Hey thanks! But since I am planning pushing everything back upstream (including my ideas about improving rouge) I think this is not needed here. :) The reason why I haven't done that yet is just the lack of time right now... Maybe next week.

**Comment by aaroneg** [comment]
That's fine, my only real goal is to get powershell highlighting working in gitlab, so whatever it takes to make that work!

**Comment by rumpelsepp** [comment]
Yeah, I will submit a pull request to gitlab that rouge actually works. As I said, probably next week. :)

**Pull request closed without merging**
